version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: task_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: